FROM jupyter/scipy-notebook:ea01ec4d9f57

RUN pip install pyarrow==0.16.0
RUN pip install spacy==2.3.0
RUN pip install Flask==1.1.2
RUN pip install textblob==0.15.3
RUN pip install langid==1.1.6
RUN pip install langdetect==1.0.8
RUN pip install gensim==3.8.0
RUN pip install geopandas==0.8.0
RUN pip install geopy==2.0.0
RUN pip install wordcloud==1.7.0
